# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Description"
  url = "#description"
  weight = 10

[[main]]
  name = "Objectives"
  url = "#outcomes"
  weight = 10

[[main]]
  name = "Resources"
  url = "#skills"
  weight = 20

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 60

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70

[[docs]]
  name = "Overview"
  url = "/docs/"
  weight = 5 

[[docs]]
  name = "Getting Started"
  weight = 10
  
[[docs]]
  name = "Resources"
  weight = 15  

[[docs]]
  name = "Module 1"
  weight = 20

[[docs]]
  name = "Module 2"
  weight = 30
  
[[docs]]
  name = "Module 3"
  weight = 40
  
[[docs]]
  name = "Module 4"
  weight = 50
  
[[docs]]
  name = "Module 5"
  weight = 60  
  
[[docs]]
  name = "Module 6"
  weight = 70
  
[[docs]]
  name = "Module 7"
  weight = 80
  
[[docs]]
  name = "Module 8"
  weight = 90
  
[[docs]]
  name = "Module 9"
  weight = 100
  
[[docs]]
  name = "Module 10"
  weight = 110
  